language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
# command to install dependencies
install:
  - pip install codecov
# command to run tests
script:
  - python3 setup.py nosetests -v --with-coverage --cover-inclusive --cover-package=org_to_anki
after_success:
  - codecov